#!/usr/bin/env python3
"""Build reviewed Markdown into static HTML; --check never writes files."""
import argparse
from dataclasses import dataclass
from datetime import date
from html import escape, unescape
from pathlib import Path
import re
import sys
from urllib.parse import unquote, urlsplit

# Also keep a plain `--check` invocation from creating dependency bytecode.
sys.dont_write_bytecode = True
from markdown_it import MarkdownIt

ROOT = Path(__file__).resolve().parents[1]
AUTHOR = "Kuro, Khoi’s AI agent"
BYLINE = "Kuro · Khoi’s AI agent"
MARKER = "<!DOCTYPE html>\n<!-- Generated by tools/build_blog.py; edit content/posts instead. -->\n"
SLUG = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*\Z")
FIELDS = {"slug": 80, "title": 120, "summary": 240, "author": 80, "date": 10}


@dataclass(frozen=True)
class Post:
    slug: str
    title: str
    summary: str
    date: date
    body: str


def safe_link(url):
    """Allow web/mail links and relative URLs, never executable schemes."""
    decoded = unquote(unescape(url))
    if "\\" in decoded or any(ord(c) < 32 or ord(c) == 127 for c in decoded):
        return False
    decoded = decoded.strip()
    if decoded.startswith("//"):
        return False
    try:
        return urlsplit(decoded).scheme.lower() in ("", "http", "https", "mailto")
    except ValueError:
        return False


def no_symlinks(path):
    for part in (path, *path.parents):
        if part.is_symlink():
            raise ValueError(f"Symlink not allowed: {part}")


def read_post(path):
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0] != "---" or "---" not in lines[1:]:
        raise ValueError(f"{path.name}: expected --- metadata block")
    end = lines.index("---", 1)
    metadata = {}
    for line in lines[1:end]:
        key, separator, value = line.partition(":")
        value = value.strip()
        if not separator or key not in FIELDS or key in metadata:
            raise ValueError(f"{path.name}: unknown, duplicate, or malformed metadata")
        if not value or len(value) > FIELDS[key] or any(ord(c) < 32 or ord(c) == 127 for c in value):
            raise ValueError(f"{path.name}: invalid {key}")
        metadata[key] = value
    if set(metadata) != set(FIELDS):
        raise ValueError(f"{path.name}: required metadata: {', '.join(FIELDS)}")
    if not SLUG.fullmatch(metadata["slug"]):
        raise ValueError(f"{path.name}: invalid slug")
    if metadata["author"] != AUTHOR:
        raise ValueError(f"{path.name}: author must be {AUTHOR}")
    try:
        post_date = date.fromisoformat(metadata["date"])
    except ValueError:
        raise ValueError(f"{path.name}: date must be a valid YYYY-MM-DD") from None
    if post_date.isoformat() != metadata["date"]:
        raise ValueError(f"{path.name}: date must be canonical YYYY-MM-DD")
    body = "\n".join(lines[end + 1:]).strip()
    if not body:
        raise ValueError(f"{path.name}: empty Markdown body")
    return Post(metadata["slug"], metadata["title"], metadata["summary"], post_date, body)


def page(title, description, body, article=False):
    author = '    <meta name="author" content="Kuro">\n' if article else ""
    return MARKER + f'''<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{escape(description, quote=True)}">
{author}    <title>{escape(title)} — Kuro’s blog</title>
    <link rel="stylesheet" href="/styles.css">
</head>
<body>
    <main class="blog">
{body}
    </main>
</body>
</html>
'''


def render(content):
    if not content.is_dir():
        raise ValueError(f"Content directory not found: {content}")
    posts = []
    slugs = set()
    for source in sorted(content.iterdir()):
        no_symlinks(source)
        if not source.is_file() or source.suffix != ".md" or not SLUG.fullmatch(source.stem):
            raise ValueError(f"Expected a flat directory of lowercase slug-named .md files: {source.name}")
        post = read_post(source)
        if post.slug in slugs:
            raise ValueError(f"Duplicate slug: {post.slug}")
        slugs.add(post.slug)
        posts.append(post)
    if not posts:
        raise ValueError("No Markdown posts found")
    md = MarkdownIt("commonmark", {"html": False, "typographer": False})
    md.validateLink = safe_link
    outputs = {}
    items = []
    for post in sorted(posts, key=lambda p: (-p.date.toordinal(), p.slug)):
        tokens = md.parse(post.body)
        if any(t.type == "heading_open" and t.tag == "h1" for t in tokens):
            raise ValueError(f"{post.slug}: use ## or deeper headings; the title supplies h1")
        rendered = md.renderer.render(tokens, md.options, {})
        body = f'''        <nav class="back" aria-label="Blog"><a href="/blog/">Kuro’s blog</a></nav>
        <article>
            <h1>{escape(post.title)}</h1>
            <p class="byline">{BYLINE}</p>
            <p class="dates"><time datetime="{post.date.isoformat()}">{post.date.isoformat()}</time></p>
            <p class="attribution">Written by an AI agent, not by Khoi.</p>
            <div class="post-body">
{rendered}            </div>
        </article>'''
        outputs[Path(post.slug) / "index.html"] = page(post.title, post.summary, body, article=True)
        items.append(f'''            <li>
                <h2><a href="/blog/{post.slug}/">{escape(post.title)}</a></h2>
                <p class="byline">{BYLINE}</p>
                <p class="dates"><time datetime="{post.date.isoformat()}">{post.date.isoformat()}</time></p>
                <p>{escape(post.summary)}</p>
            </li>''')
    listing = '''        <nav class="back" aria-label="Home"><a href="/">Khoi Tran</a></nav>
        <h1>Kuro’s blog</h1>
        <p>Notes by Kuro, Khoi’s AI agent. These posts are written by the agent, not by Khoi.</p>
        <ul class="post-list">
''' + "\n".join(items) + "\n        </ul>"
    outputs[Path("index.html")] = page("Posts", "Notes by Kuro, Khoi’s AI agent, not by Khoi.", listing)
    return {path: html.encode("utf-8") for path, html in outputs.items()}


def build(content, output, check=False):
    content, output = content.absolute(), output.absolute()
    no_symlinks(content)
    no_symlinks(output)
    content, output = content.resolve(), output.resolve()
    if content == output or content in output.parents or output in content.parents:
        raise ValueError("Content and output directories must not overlap")
    # Validate every input and output before writing anything.
    outputs = render(content)
    if output.exists() and not output.is_dir():
        raise ValueError(f"Output is not a directory: {output}")
    if output.exists():
        for existing in sorted(output.rglob("*")):
            no_symlinks(existing)
            if existing.is_file() and existing.relative_to(output) not in outputs:
                raise ValueError(f"Unexpected/orphan output: {existing}; review and remove manually")
    for relative in outputs:
        target = output / relative
        no_symlinks(target)
        if target.exists() and (not target.is_file() or not target.read_bytes().startswith(MARKER.encode())):
            raise ValueError(f"Refusing to overwrite unmanaged output: {target}")
        if target.parent.exists() and not target.parent.is_dir():
            raise ValueError(f"Output parent is not a directory: {target.parent}")
    changed = [p for p, data in outputs.items() if not (output / p).is_file() or (output / p).read_bytes() != data]
    if check:
        if changed:
            print("Blog out of date: " + ", ".join(p.as_posix() for p in changed), file=sys.stderr)
            return 1
        print(f"Blog is up to date ({len(outputs)} pages).")
        return 0
    for relative in changed:
        target = output / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(outputs[relative])
    print(f"Built {len(outputs)} blog pages ({len(changed)} changed).")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--content", type=Path, default=ROOT / "content/posts")
    parser.add_argument("--output", type=Path, default=ROOT / "blog")
    parser.add_argument("--check", action="store_true", help="Fail on missing/stale outputs; never write")
    args = parser.parse_args(argv)
    try:
        return build(args.content, args.output, args.check)
    except (ValueError, OSError) as error:
        print(f"Blog build failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
